import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/components/Layout/LayoutProvider";
import Navbar from "@/components/Header/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crown Travels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/images/logo.png" />
      </head>
      <body className={inter.className}>
        <Navbar/>
        <LayoutProvider>
        {children}
        </LayoutProvider>
        <Footer/>
        </body>
    </html>
  );
}
